import './globals.css';
import Image from 'next/image';
import { execSync } from 'child_process';
import github_logo from './assets/github_logo.svg';
import linkedin_logo from './assets/linkedin_logo.png';
// import itchio_logo from './assets/itchio_logo.svg';
// import devpost_logo from './assets/devpost_logo.svg';

function getCommitHash() {
  if (process.env.VERCEL_GIT_COMMIT_SHA) {
    return process.env.VERCEL_GIT_COMMIT_SHA.slice(0, 7);
  }

  try {
    return execSync('git rev-parse --short HEAD').toString().trim();
  } catch {
    return null;
  }
}

export default function Home() {

  const commitHash = getCommitHash();

  return (
    <div className="Home" style={{display: "flex", flexDirection: "column", justifyContent: "center", overflow: "hidden"}}>
      <div className="all-content">
        <div className="title">
          <h1>hey! i'm sofia :D</h1>
          <h2>
            i'm a freshman at <a className="link" href="https://web.mit.edu">MIT</a> studying computer science and i work at <a className="link" href="https://hackclub.com">Hack Club</a>!
            i go by <span className="tooltip">eeriergosling<span className="tooltip-text">this was a username generated by xbox many years ago, and it's stuck since!</span></span> online.
          </h2>
          <p>
            i love building things, especially software! i've done a wide variety of technical work - from web development to hardware to games. you can see some of the things i've built on my <a className="link" href="/projects">projects page</a>!
          </p>
          <p>
            at <a className="link" href="https://hackclub.com">hack club</a>, i run programs to get teens into tech! joining hack club as a freshman in high school taught me that you can just <i>do things</i> if you simply believe you can, 
            and i've been trying to inspire other teens to do the same since. i've led {" "}
            <a className="link tooltip" href="https://horizons.hackclub.com">horizons<span className="tooltip-text">a series of 6 hackathons around the world in san francisco, sydney, berlin, singapore, toronto, and cairo (summer 2026)</span></a>, {" "}
            <a className="link tooltip" href="https://shipwrecked.hackclub.com">shipwrecked<span className="tooltip-text">a 4-day hackathon on an island in the boston harbor for 110 teens from around the world (august 8-11, 2025)</span></a>, and {" "}
            <a className="link tooltip" href="https://counterspell.hackclub.com"> counterspell<span className="tooltip-text">50 concurrent game jams all around the world (november 23-24, 2024)</span></a>, {" "}
            which together inspired at least 4,000 teens to build technical projects and cost nearly half a million dollars.
          </p>
          <p className="subtitle">
            {commitHash && (
              <>
                {" "}commit{" "}
                <a className="link" href={`https://github.com/eeriergosling/site/commit/${commitHash}`}>{commitHash}</a>
                ,{" "}
              </>
            )}
            open source at <a className="link" href="https://github.com/eeriergosling/site">eeriergosling/site</a>
          </p>
          <div style={{display: "flex", alignItems: "center"}}>
            <a href="https://github.com/EerierGosling">
              <Image className="social-link" src={github_logo} alt="github logo" width={50} height={50} />
            </a>
            <a href="https://www.linkedin.com/in/sofia-egan">
              <Image className="social-link" src={linkedin_logo} alt="linkedin logo" width={50} height={50} />
            </a>
            <span className="social-link tooltip icon-tooltip">
              <svg width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{transform: "translateY(-3px) scale(1.21)"}}>
                <path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z" />
                <polyline points="22 6 12 13 2 6" />
              </svg>
              <span className="tooltip-text">sofia at eerier dot dev</span>
            </span>

            {/* <a href="https://eeriergosling.itch.io/">
              <Image className="social-link" src={itchio_logo} alt="Itch.io Logo" width={50} height={50} />
            </a>
            <a href="https://devpost.com/eeriergosling">
              <Image className="social-link" src={devpost_logo} alt="Devpost Logo" width={50} height={50} />
            </a> */}
          </div>
        </div>
      </div>
    </div>
  );
}
